-- Create the tasks table
-- VEDERNIX Database Setup
CREATE TABLE IF NOT EXISTS pending_users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password text NOT NULL, -- Temporarily storing plain password for admin review, should be hashed for production
    full_name text NOT NULL,
    site_username text NOT NULL,
    referral_site text NOT NULL,
    proof_image_url text,
    admin_notes text,
    rejection_reason text
);
-- 1. جدول المواقع (Sites)
CREATE TABLE sites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name text NOT NULL UNIQUE,
    site_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. جدول إعدادات المستخدم (User Settings)
CREATE TABLE user_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) NOT NULL UNIQUE,
    goal_type text DEFAULT 'daily',
    daily_goal_rubles double precision DEFAULT 100.0,
    monthly_goal_rubles double precision DEFAULT 3000.0,
    sites text[] DEFAULT ARRAY[]::text[],
    language_code text DEFAULT 'en',
    account_status text DEFAULT 'pending' NOT NULL, -- 'pending', 'approved', 'rejected'
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. جدول المهمات الأساسي (Tasks)
CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_title text NOT NULL,
    task_video_url text, 
    uploaded_video text, 
    completed_count int DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. جدول تفاصيل المهمة لكل موقع (Task Sites)
CREATE TABLE task_sites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint REFERENCES tasks(id) ON DELETE CASCADE,
    site_name text NOT NULL,
    task_link text NOT NULL,
    price double precision DEFAULT 0.0,
    max_users int DEFAULT 1,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. جدول المهمات المكتملة (Completed Tasks)
CREATE TABLE completed_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) NOT NULL,
    task_id bigint REFERENCES tasks(id) ON DELETE CASCADE,
    site_name text NOT NULL,
    executed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Profiles table for VEDERNIX (Safe migration)
-- إضافة الأعمدة الجديدة فقط في حال عدم وجودها
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS user_type text DEFAULT 'user';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS full_name text; 
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS username text; -- For Advertisers
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS site_usernames jsonb DEFAULT '{}'::jsonb; -- Storage for multiple site usernames
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referral_site text; -- Keep for legacy
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS role text DEFAULT 'user';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS country text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text;

-- الحقول الـ 5 الإضافية
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS balance double precision DEFAULT 0.0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS total_earned double precision DEFAULT 0.0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referral_code text UNIQUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS language_preference text DEFAULT 'en';

-- Ensure existing users are approved
-- Set an initial admin (Replace with your actual email)
-- UPDATE profiles SET role = 'admin', status = 'approved' WHERE id IN (SELECT id FROM auth.users WHERE email = 'your-admin@email.com');

-- Ensure existing data consistency
UPDATE profiles SET status = 'approved' WHERE status IS NULL;
UPDATE profiles SET role = 'user' WHERE role IS NULL AND user_type = 'user';

-- Create index for performance
CREATE INDEX IF NOT EXISTS idx_status ON profiles(status);

-- تفعيل سياسات الأمان لجميع الجداول
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE completed_tasks ENABLE ROW LEVEL SECURITY;

-- RLS for pending_users: Allow anonymous users to insert their registration requests
DROP POLICY IF EXISTS "Allow anonymous insert to pending_users" ON pending_users;
CREATE POLICY "Allow anonymous insert to pending_users" ON pending_users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow user to insert own settings" ON user_settings;
DROP POLICY IF EXISTS "Allow user to update own settings" ON user_settings;
DROP POLICY IF EXISTS "Allow user to read own settings" ON user_settings;
CREATE POLICY "Public read all" ON sites FOR SELECT USING (true);
CREATE POLICY "Public read tasks" ON tasks FOR SELECT USING (true);
CREATE POLICY "Public insert tasks" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update tasks" ON tasks FOR UPDATE USING (true);
CREATE POLICY "Public read task_sites" ON task_sites FOR SELECT USING (true);
CREATE POLICY "Public insert task_sites" ON task_sites FOR INSERT WITH CHECK (true);

CREATE POLICY "insert_own" ON user_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own" ON user_settings FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "select_own" ON user_settings FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users completion" ON completed_tasks FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

INSERT INTO sites (site_name, site_url) VALUES 
('seofast', 'https://seo-fast.ru'),
('aviso', 'https://aviso.bz'),
('socpublic', 'https://socpublic.com')
ON CONFLICT (site_name) DO NOTHING;

-- جداول حفظ اللغة المستقلة
CREATE TABLE IF NOT EXISTS user_language (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    language_code text NOT NULL DEFAULT 'en'
);

CREATE TABLE IF NOT EXISTS advertiser_language (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    language_code text NOT NULL DEFAULT 'en'
);

ALTER TABLE user_language ENABLE ROW LEVEL SECURITY;
ALTER TABLE advertiser_language ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- STORAGE SETUP (Safe Configuration)
-- ==========================================

-- Create bucket for user uploads
INSERT INTO storage.buckets (id, name, public)
VALUES ('user_uploads', 'user_uploads', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for storage.objects
-- Note: We do NOT use ALTER TABLE on storage.objects as it causes permission errors
DROP POLICY IF EXISTS "Allow Public View" ON storage.objects;
CREATE POLICY "Allow Public View" ON storage.objects FOR SELECT USING (bucket_id = 'user_uploads');

DROP POLICY IF EXISTS "Allow Anonymous Uploads" ON storage.objects;
CREATE POLICY "Allow Anonymous Uploads" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'user_uploads');

-- Reload PostgREST Cache
SELECT pg_notify('pgrst', 'reload schema');