-- Create the tasks table
-- VEDERNIX Database Setup
DROP TABLE IF EXISTS completed_tasks CASCADE;
DROP TABLE IF EXISTS task_sites CASCADE;
DROP TABLE IF EXISTS user_settings CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS sites CASCADE;
DROP TABLE IF EXISTS profiles CASCADE;

-- Add pending_users table for restricted registration
CREATE TABLE IF NOT EXISTS pending_users (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    email text NOT NULL UNIQUE,
    password text NOT NULL, -- Temporarily storing plain password for admin review, should be hashed for production
    full_name text NOT NULL,
    site_username text NOT NULL,
    referral_site text NOT NULL,
    proof_image_url text NOT NULL,
    status text DEFAULT 'pending' NOT NULL, -- 'pending', 'approved', 'rejected'
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- 1. جدول المواقع (Sites)
CREATE TABLE sites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_name text NOT NULL UNIQUE,
    site_url text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. جدول إعدادات المستخدم (User Settings)
CREATE TABLE user_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) NOT NULL UNIQUE,
    goal_type text DEFAULT 'daily',
    daily_goal_rubles double precision DEFAULT 100.0,
    monthly_goal_rubles double precision DEFAULT 3000.0,
    sites text[] DEFAULT ARRAY[]::text[],
    language_code text DEFAULT 'en',
    account_status text DEFAULT 'pending' NOT NULL, -- 'pending', 'approved', 'rejected'
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

-- 3. جدول المهمات الأساسي (Tasks)
CREATE TABLE tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_title text NOT NULL,
    task_video_url text, 
    uploaded_video text, 
    completed_count int DEFAULT 0,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. جدول تفاصيل المهمة لكل موقع (Task Sites)
CREATE TABLE task_sites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint REFERENCES tasks(id) ON DELETE CASCADE,
    site_name text NOT NULL,
    task_link text NOT NULL,
    price double precision DEFAULT 0.0,
    max_users int DEFAULT 1,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. جدول المهمات المكتملة (Completed Tasks)
CREATE TABLE completed_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) NOT NULL,
    task_id bigint REFERENCES tasks(id) ON DELETE CASCADE,
    site_name text NOT NULL,
    executed_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Profiles table for VEDERNIX (Safe migration)
-- إضافة الأعمدة الجديدة فقط في حال عدم وجودها
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS user_type text DEFAULT 'user';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS country text;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio text;

-- الحقول الـ 5 الإضافية
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS balance double precision DEFAULT 0.0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS total_earned double precision DEFAULT 0.0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referral_code text UNIQUE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS is_verified boolean DEFAULT false;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS language_preference text DEFAULT 'en';

-- تفعيل سياسات الأمان لجميع الجداول
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_sites ENABLE ROW LEVEL SECURITY;
ALTER TABLE completed_tasks ENABLE ROW LEVEL SECURITY;

-- RLS for pending_users: Allow anonymous users to insert their registration requests
DROP POLICY IF EXISTS "Allow anonymous insert to pending_users" ON pending_users;
CREATE POLICY "Allow anonymous insert to pending_users" ON pending_users FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow user to insert own settings" ON user_settings;
DROP POLICY IF EXISTS "Allow user to update own settings" ON user_settings;
DROP POLICY IF EXISTS "Allow user to read own settings" ON user_settings;
CREATE POLICY "Public read all" ON sites FOR SELECT USING (true);
CREATE POLICY "Public read tasks" ON tasks FOR SELECT USING (true);
CREATE POLICY "Public insert tasks" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Public update tasks" ON tasks FOR UPDATE USING (true);
CREATE POLICY "Public read task_sites" ON task_sites FOR SELECT USING (true);
CREATE POLICY "Public insert task_sites" ON task_sites FOR INSERT WITH CHECK (true);

CREATE POLICY "insert_own" ON user_settings FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "update_own" ON user_settings FOR UPDATE TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "select_own" ON user_settings FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users completion" ON completed_tasks FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

INSERT INTO sites (site_name, site_url) VALUES 
('seofast', 'https://seo-fast.ru'),
('aviso', 'https://aviso.bz'),
('socpublic', 'https://socpublic.com')
ON CONFLICT (site_name) DO NOTHING;

-- جداول حفظ اللغة المستقلة
CREATE TABLE IF NOT EXISTS user_language (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    language_code text NOT NULL DEFAULT 'en'
);

CREATE TABLE IF NOT EXISTS advertiser_language (
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    language_code text NOT NULL DEFAULT 'en'
);

ALTER TABLE user_language ENABLE ROW LEVEL SECURITY;
ALTER TABLE advertiser_language ENABLE ROW LEVEL SECURITY;

-- Reload PostgREST Cache
SELECT pg_notify('pgrst', 'reload schema');